### PR TITLE
Milestone 2 - User Interface

### PR DESCRIPTION
**Pull request by fernandorpm**
# Milestone 2 - User Interface
> On this milestone we're supposed to code the basic interface (non-functional) of the project. This code is not final, some of it will be replaced in the next sessions. Check it out on pathwright: https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/

## To update :heavy_check_mark: 
- bin/main.rb
- README.md

## To delete :x: 
- .gitignore
## To take note :spiral_notepad: 
- The README will have the Live Demo version as well as the explanation about what is and how to play the Tic Tac Toe Game on the last Milestone - Instruction to Players.

### CODE REVIEW

**Review by ElijahTobs — COMMENTED** [review]
# Status: 🚨 ❌ INVALID ❌ 🚨 

## Hi @fernandorpm :wave: 

### This project has been marked as invalid because you did not follow the [Git Flow guidelines](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/).

### The Pull Request is supposed to be from your feature branch to the development branch, not to the main branch as you've done here.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by fernandorpm** [comment]
## Changed the base branch from main to development
My bad, I just forgot about it. Fixed already.

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @fernandorpm  :wave:

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

- [x] game informs player if the selected move is a draw move (without computing draw). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_tie.png)

#### See the gif below for more clarity:
image


## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by fernandorpm** [comment]
## For the next reviewer :rocket: 
On the 4th move, the game will print that it is a DRAW! And then, you'll have to press enter in order to proceed and finish the game, wherein the end it will print that it is a WIN!

This is because there's no game logic yet, so the intention is just to show you that both possible results have been designed already!

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED 
--------------
Hello @fernandorpm  you did an amazing job in this milestone :clap: I really like your code is really clean and clear. Also, I like that you are really professional in your repository. Keep being this professional. :muscle: :smile: 
-------
You can merge this branch now :+1: :1st_place_medal: 
If you have any questions reach me on SLACK 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!! AND GOOD LUCK IN THE NEXT MILESTONE :smile: 

tenor

**Pull request merged**
